### PR TITLE
Fix common window border radius problems when it get maximized

### PR DESCRIPTION
**Pull request by rivanfebrian123**
Still had some problem with rounded corners, so I make this pull request to solve these window rounded corner problems, for example:
- Nautilus left bottom corner
- Gedit left and right bottom corners

 Anyways, all of the CSS here is generated with `parse-sass. sh`. So, yeah, don't worry. They're all automatically generated :)
I also update the previous Firefox CSS code commit

### CODE REVIEW

**Comment by vinceliuice** [comment]
Why delete all sidebar assets files?

**Comment by rivanfebrian123** [comment]
Oh no! Actually, I initially want to request my "fix the common window border radius issue and give the firefox css code a better sense" and "Fix common window border radius problems when it get maximized" **only** but I didn't create a new branch for "fixes #7, fixes #23, fixes #45, fixes #70", so yeah. This is what happened.


Please let me continue my work and don't merge this pull request but don't close it

**Comment by vinceliuice** [comment]
I fixed this now

**Comment by rivanfebrian123** [comment]
Vince, I think its gonna take longer than I thoght

**Pull request closed without merging**
