### PR TITLE
New Installation Framework

### LINKED ISSUE #23: Nautilus, left column not increase at text length
In nautilus, left column is small, and my google account overlap.
I can't resize.
image

another thing, when pass the mouse hover, the background of items not refresh.

Best Regards

### LINKED ISSUE #45: 一些小问题
首先十分感谢您优秀的主题。

GTK和icon有以下的问题：
1. Nautilus左边列表的大小无法和标题一起调整。(这个问题能修么?)  
2. Gnome Shell的状态栏图表大小不一。(或许是上游问题?)

问题截图：
Screenshot from 2020-09-12 17-50-51

### LINKED ISSUE #50: Weird glitches can't login
Once I installed the themes (Pop!_OS), my screen glitched a little and I was sent to the login screen, where I can't do much, because when trying to login I get the same behavior.

### LINKED ISSUE #58: Gedit has 90 degrees border radius on bottom left and bottom right.
With this theme, open gedit (it's not gedit specific btw) and notice that the bottom left and bottom right has a 90 degrees border.

It applies to gnome-terminal too. I don't think it should be 90 degrees... right?

Screenshot from 2020-11-01 22-21-44

Screenshot from 2020-11-01 22-22-03

### LINKED ISSUE #70: Nautilus sidebar background doesn't get wider when resizing it
Nautilus' left navbar background is set at a fixed width. It should expand when the sidebar is resized, however.

<details>
  <summary>Default look</summary>

Schermata da 2020-11-18 19-16-50
  
</details>

<details>
  <summary>How it looks when the sidebar is resized</summary>

Schermata da 2020-11-18 19-17-03
  
</details>

<details>
  <summary>How it should look</summary>

Schermata da 2020-11-18 19-17-25
  
</details>

### LINKED ISSUE #80: WhiteSur-dark: nautilus side bar artifacts
When moving the mount up and down the nautilus sidebar artifact remains long after. This is visually distracting. The problem does not occur in the non-transparent versions. the Arc theme also has a transparent sidebar in nautilus and does not have this issue. Borrow some code?

Screenshot from 2020-12-03 10-16-04

### LINKED ISSUE #113: [Query] How do I change the default big sur wallpaper in GDM theme?
I've installed the GDM theme via `sudo ./install -g`. I see that the login screen has changed as mentioned in the readme.md.
However, I'd like to change the default Big Sur wallpaper that is being displayed as the login screen background. What do I need to do to change that specific wallpaper?

Thx

### LINKED ISSUE #126: snap icon theme and gtk theme not working for all apps except snap store
I installed the snap theme for my snap apps so that i can integrate my ubuntu into one theme. But after i connected the gtk3 theme and icon theme to all apps using the command given in the readme. But its only working for the snap store, apps like gimp are not accepting the theme.
Steps to reproduce:
1. sudo snap install whitesur gtk theme
2. then connect the theme to all apps
3. Will not work for any apps except snap store.

Screenshot from 2021-01-30 19-49-59

As in the screenshot, the gimp icon did not update to the icon theme's icon. I did restart.

Screenshot from 2021-01-30 19-50-25

In this screenshot the gimp system theme was supposed to change but it looks just like the default system theme. Please adress this issue.

### LINKED ISSUE #138: "Activities" icon not working
I set `-i ubuntu` on installation, but even after <kbd>Alt</kbd><kbd>F2</kbd>, <kbd>r</kbd> and a full reboot, I don't see anything.

## Images
image
___
**On hover:**

image

### LINKED ISSUE #145: Text is over out/bad truncate the dialog box in Zorin OS 15.3 Core
Screenshot from 2021-03-05 10-33-24
Screenshot from 2021-03-05 10-33-54

### LINKED ISSUE #146: The `--remove` command doesn't work
So I'm new to this theme and I loved it very much and also this amazing. I always wanted to have Mac OS but I can't afford to it and buy the os also I don't have a PC that atleast runs GNOME. SO Im stuck with XFCE. But when I installed it it was good and tried 3 colors and wanted to have red. When I used `sudo ./install.sh -r -t green -g` it says `DONE!` but the theme is still visible in the manager and I can change to it. I tried to close the settings manager and open the themes menu again, it was still there and working. So now how do I remove the theme.

### LINKED ISSUE #149: Gnome contacts issue
The dotted line on the bottom left indicating to show more content when scrolling down is shown out of the corner.

Bildschirmfoto vom 2021-03-13 08-37-13

Edit: This issue is also present in totem and settings, probably in every app with the dotted line on the bottom.

Bildschirmfoto vom 2021-03-14 07-57-39
Bildschirmfoto vom 2021-03-14 07-57-58

Edit: Issue already reported here: https://github.com/vinceliuice/WhiteSur-gtk-theme/issues/7

### LINKED ISSUE #152: This bar in trash folder looks broken (Gnome Files)
Pretty self explanatory, I've added an screenshot which explains better. Also the contrast for the disabled **Restore** button should be improved.

image12

Thanks for your works anyway, I like most of your themes, both Plasma and Gnome. 👌

### LINKED ISSUE #156: nautilus sidebar
Please can you add the sidebar of nautilus to be sizeable and color of sidebar be the same as we increase the area of the sidebar?
Now the theme looks odd for the sidebar

### LINKED ISSUE #164: dash-to-dock error "stylesheet.css does not exist"
I am trying to install the dash to dock but i get the error "stylesheet.css does not exist". I have checked and the file exists and has stuff in it. What am I doing wrong?

### LINKED ISSUE #165: [bug] Unmount button is in wrong place // sidebar width size doesnt change all setting
I tried to change the Nautilus sidebar width size, now the unmount button is displayed in the wrong place
I am on PopOS 20.10, Gnome 3.38.3 with PopShell plugin, I am using Ultrawide monitor
image

The unmount button is tied to the body of the file manager, not the sidebar - manipulating the width of the body moves the button to the right place, but this is unexpected behaviour for me.

image

### PR DESCRIPTION
**Pull request by rivanfebrian123**
Hi Vince, I really love your theme, so I decided to make it better... And I'm so glad that I can finally finish this project. Anyways, I really wanna thank you for your effort making this theme. Maybe I'll make a donation for you someday :). And yeah, here's the changelog:

# Changelog
## Improved installation speed and stability
speed-164063_640

I've done some test here in my old gen i3 HP notebook.

#### Test command: `time ./install.sh`
Result of the old WhiteSur installer:

```bash
real	0m0.531s
user	0m0.238s
sys	0m0.287s
```

Result of the new WhiteSur installer:

```bash
real	0m1.340s
user	0m2.485s
sys	0m0.600s
```

Summary: around 2 times slower than the old one

#### Test command: `time ./install.sh -s 240`
Result of the old WhiteSur installer:

```bash
real	0m31.778s
user	0m28.134s
sys	0m2.880s
```

Result of the new WhiteSur installer:

```bash
real	0m1.322s
user	0m2.483s
sys	0m0.570s
```

Summary: around 30 times faster than the old one

#### Test command: `time ./install.sh`
Result of the old WhiteSur installer:

```bash
real	0m31.619s
user	0m28.537s
sys	0m2.957s
```

Result of the new WhiteSur installer:

```bash
real	0m1.277s
user	0m2.465s
sys	0m0.567s
```

Summary: around 30 times faster than the old one

#### Test command: `time ./install.sh -s 240`
Result of the old WhiteSur installer:

```bash
real	0m31.271s
user	0m28.273s
sys	0m2.882s
```

Result of the new WhiteSur installer:

```bash
real	0m1.289s
user	0m2.487s
sys	0m0.609s
```

Summary: around 30 times faster than the old one

## Improved error handling and security
chain-3481377_640

Some bug like unexpected loops when running `./install.sh -d` (without any value) has been fixed. Spaces in source and destination path shouldn't be a problem anymore.

In this version, we don't write CSS-es in the source directory, instead, we write them to the temporary directory. We also block an installer instance from running if the other one is already running.

## More customizations
pencils-452238_640

You can now change the GDM background and customize it, and change the Nautilus style. But, there's some known bugs tho.... You can read them in `CONTRIBUTING.md`

## One 'click' installation
hand-2111445_640

The installers can now automatically install dependencies when you install something, but currently, it only supports the most popular distros. But don't worry, I'm trying to add a support for some least popular distros like Void Linux, Calculate Linux (Gentoo OS-based Linux), etc. I even open an issue here at https://github.com/void-linux/void-packages/issues/30066.

In the `tweaks.sh`, you can also install the Firefox theme and edit it, install Dash to Dock theme, and connecting WhiteSur to Snap and Flatpak automatically.

## New framework
gear-192875_640

Now we have rich libraries to improve the project maintainability and to make it easier to extend some features. As I mentioned before, we don't generate the CSS-es in the source directory anymore to make it easier to review every new commits. But yeah, it's not yet documented, sorry :)

## Limitation
road-690347_640

Currently, for GNOME 40, I use a custom background for Nautilus window to make the header transparent because if I just use a solid color (with transparancy, obviously), the Nautilus glassy style doesn't looks so good cuz it looks so opaque. I will try to get in touch with GNOME developers about this, insha Allah

## Other fixed bugs
* fixed #165
* fixed #164
* fixed #156
* fixed #152
* fixed #149
* fixed #146
* fixed #145
* fixed #138
* fixed #126
* fixed #113
* fixed #80
* fixed #70
* fixed #58
* fixed #50
* fixed #45
* fixed #23

### CODE REVIEW

**Comment by vinceliuice** [comment]
Thank you for everything you have done for this theme!

**Comment by rivanfebrian123** [comment]
You're welcome :)

**Comment by fd6130** [comment]
> You're welcome :)

Kindly note that issue #145 still exist in Zorin 15.3 because of the gnome version they are using.

**Comment by rivanfebrian123** [comment]
> @rivanfebrian123
> 
> Kindly note that issue #145 still exist in Zorin 15.3 because of the gnome version they are using.

Could you try my repo please? https://github.com/rivanfebrian123/WhiteSur-gtk-theme
It's actually different with Vince's repo since this merge

**Comment by fd6130** [comment]
> > @rivanfebrian123
> > Kindly note that issue #145 still exist in Zorin 15.3 because of the gnome version they are using.
> 
> Could you try my repo please? https://github.com/rivanfebrian123/WhiteSur-gtk-theme
> It's actually different with Vince's repo since this merge

I tried it just now, the issue still persist. What is your gnome version? Mine is 3.30. 

Should i remove all the themes from this repo and run `./install.sh` again?

**Comment by rivanfebrian123** [comment]
> > > @rivanfebrian123
> > > Kindly note that issue #145 still exist in Zorin 15.3 because of the gnome version they are using.
> > 
> > 
> > Could you try my repo please? https://github.com/rivanfebrian123/WhiteSur-gtk-theme
> > It's actually different with Vince's repo since this merge
> 
> I tried it just now, the issue still persist. What is your gnome version? Mine is 3.30. It occurs when i choose Whitesur as my shell theme.
> 
> Should i remove all the themes from this repo and run `./install.sh` again?

Already tested the theme on ZorinOS again (the freshly installed one) and got this conclution: you need to install WhiteSur GDM theme too to fix that problem

**Comment by fd6130** [comment]
> > > > @rivanfebrian123
> > > > Kindly note that issue #145 still exist in Zorin 15.3 because of the gnome version they are using.
> > > 
> > > 
> > > Could you try my repo please? https://github.com/rivanfebrian123/WhiteSur-gtk-theme
> > > It's actually different with Vince's repo since this merge
> > 
> > 
> > I tried it just now, the issue still persist. What is your gnome version? Mine is 3.30. It occurs when i choose Whitesur as my shell theme.
> > Should i remove all the themes from this repo and run `./install.sh` again?
> 
> Already tested the theme on ZorinOS again (the freshly installed one) and got this conclution: you need to install WhiteSur GDM theme too to fix that problem

Not sure what happen though, the problem still persist. I will try fresh install Zorin in Virtualbox and try again.

**Comment by rivanfebrian123** [comment]
Make sure you install only the latest WhiteSur themes from my repo or Vince's, and you install the GTK themes only in one directory (root or user one), **not** both root and user

**Comment by fd6130** [comment]
> Make sure you install only the latest WhiteSur themes from my repo or Vince's, and you install the GTK themes only in one directory (root or user one), **not** both root and user

Can provide a screenshot from your screen? I wanna see how it looks like.

**Comment by fd6130** [comment]
@rivanfebrian123 Here are the screenshot of mine:

Screenshot from 2021-04-08 21-35-07

Screenshot from 2021-04-08 21-35-12

**Pull request merged**
