### PR TITLE
Fixed dark theme

### PR DESCRIPTION
**Pull request by d3lfs**
- I change the dark theme color to be more darker
- fixed large height of header bar to small
- fixed window corner to be more MACOS realistic

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
Any update on this?

**Comment by slypy** [comment]
> Any update on this?

still working on this to new branch for gnome 42

**Comment by slypy** [comment]
@vinceliuice there is still no option for the window activity button resizer?

**Comment by fr3nchalp4a** [comment]
Updates ?

**Comment by ThatOneCalculator** [comment]
:confused:

**Pull request closed without merging**
