### PR TITLE
Firefox: fix website title centring with no favicon #262

### PR DESCRIPTION
**Pull request by AdamXweb**

### CODE REVIEW

**Review by rivanfebrian123 — COMMENTED** [review]
Looks good! I'm testing now

BTW, you can tidy up your code in the mean time

**Comment by rivanfebrian123** [comment]
Screenshot from 2021-05-30 17-24-58
@vinceliuice it doesn't work here

**Comment by vinceliuice** [comment]
No works for version 88, I'll make it back

**Comment by AdamXweb** [comment]
Sorry I may have forgotten some other code I had added that makes the logic work correctly.. give me a few mins and I'll update

**Comment by AdamXweb** [comment]
#277
Have included updates

**Pull request merged**
